import { PrismaClient } from '../generated/prisma/client.js';
import { PrismaPg } from '@prisma/adapter-pg';
import { config } from 'dotenv';

config({ path: '.env' });

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL! }) as never,
});

type B = { type: string; text: string };
const p  = (text: string): B => ({ type: 'p',   text });
const h2 = (text: string): B => ({ type: 'h2',  text });
const h3 = (text: string): B => ({ type: 'h3',  text });
const c  = (text: string): B => ({ type: 'code', text });
const ul = (text: string): B => ({ type: 'ul',  text });
const tb = (text: string): B => ({ type: 'table', text });

const posts = [
  // ─── 1: How to Learn Web Development ──────────────────────────────────────
  {
    slug:        'how-to-learn-web-development',
    title:       'How to Learn Web Development in 2025: A Realistic Roadmap for Beginners',
    excerpt:     'Wondering how to start learning web development? This guide gives you a realistic, ordered path from zero to building your first website — with no fluff.',
    author:      'Elvar',
    tag:         'GUIDE',
    gem:         '/gem/gem-33.png',
    readTime:    10,
    isPublished: true,
    order:       1,
    body: [
      p('Most "learn web dev" guides start with a list of 40 technologies and a vague instruction to "pick one." This guide doesn\'t do that. It gives you one ordered path, the reasoning behind the order, and realistic expectations about how long each step takes.'),
      h2('The Reality Check First'),
      p('Web development is learnable. You don\'t need a computer science degree. You don\'t need to be good at math. You don\'t need to have coded before.'),
      p('But here\'s what most guides don\'t say clearly enough: the hardest part isn\'t the syntax, it\'s staying consistent. Every person who "couldn\'t learn to code" either started in the wrong place, used the wrong resources, or stopped before things started to click. Skills compound — the first month is the hardest, and most people quit in the first month.'),
      h2('Phase 1: HTML (1–2 Weeks)'),
      p('HTML is the first language you learn. There are no alternatives, no shortcuts, no "skip straight to JavaScript."'),
      p('What you\'ll learn:'),
      ul('The structure of an HTML document\nCommon tags: headings, paragraphs, links, images, lists, forms\nSemantic HTML: using the right element for the right purpose\nHow browsers read and render HTML'),
      p('HTML is not a programming language. It has no logic, no conditions, no loops. It describes structure, not behavior. This is why you can learn the basics in a week or two.'),
      p('When you\'re ready to move on: when you can write a multi-page HTML document from memory — with a proper head, semantic structure, working links between pages, and a form with labels.'),
      h2('Phase 2: CSS (3–5 Weeks)'),
      p('CSS is where beginners often get frustrated. The language is simple to write but complex to reason about — especially layouts.'),
      p('What you\'ll learn:'),
      ul('Selectors, properties, and values\nThe box model (critical — don\'t skip this)\nTypography and color\nFlexbox for one-dimensional layouts\nCSS Grid for two-dimensional layouts\nResponsive design with media queries\nCSS custom properties (variables)'),
      p('CSS has internal logic — specificity, cascade, inheritance — that isn\'t obvious until you\'ve broken things a few times. Layout in particular requires building a mental model, not just memorizing properties.'),
      p('When you\'re ready to move on: when you can take a design and build it in HTML + CSS that looks right on both desktop and mobile.'),
      h2('Phase 3: JavaScript Fundamentals (4–6 Weeks)'),
      p('JavaScript is your first real programming language. This is where logical thinking matters more than memorization.'),
      p('What you\'ll learn:'),
      ul('Variables and data types\nOperators and comparisons\nConditionals (if/else, switch)\nLoops (for, while, for...of)\nFunctions (declarations, expressions, arrow functions)\nArrays and objects\nCommon built-in methods'),
      p('JavaScript requires you to think procedurally — to describe steps, not just structures. Don\'t rush to frameworks. Beginners who skip JS fundamentals to go straight to React spend months debugging problems they don\'t understand because they don\'t know the underlying language.'),
      p('When you\'re ready to move on: when you can write functions, loop through data, and handle conditional logic without having to look up the syntax constantly.'),
      h2('Phase 4: DOM Manipulation (2–3 Weeks)'),
      p('The DOM is the bridge between HTML and JavaScript. This is where you learn to make pages interactive.'),
      p('What you\'ll learn:'),
      ul('What the DOM is and how browsers build it\nSelecting elements (querySelector, querySelectorAll)\nReading and writing content (textContent, innerHTML)\nModifying classes and styles\nCreating and removing elements\nResponding to user events with addEventListener\nEvent delegation'),
      p('When you\'re ready to move on: when you can build a working interactive interface using vanilla JavaScript — something that responds to user input and changes what\'s on screen.'),
      h2('Phase 5: A Capstone Project (2–4 Weeks)'),
      p('Before moving to any framework, build something. Not a tutorial. Not a follow-along project. Something you designed, broke, fixed, and shipped yourself.'),
      p('Ideas for scope:'),
      ul('A personal portfolio with working sections\nA todo or habit tracker\nA quiz app\nA weather app (you\'ll need to learn the Fetch API for this)\nA simple game'),
      p('Tutorials give you the illusion of progress. Building something original reveals exactly what you actually understand and what you\'re still fuzzy on. The gaps that appear are precisely what you should study next.'),
      h2('What Comes After'),
      p('Once you have solid fundamentals and a project, you have real choices:'),
      ul('React — The industry standard for building dynamic user interfaces. React is built on top of HTML + CSS + JS, not a replacement. Skipping fundamentals makes React confusing.\nNode.js — Taking JavaScript server-side. Handling databases, APIs, authentication, and business logic.\nTypeScript — A typed superset of JavaScript that catches errors before you run your code. Most professional codebases use it.\nCSS frameworks (Tailwind) — Utility-first CSS that speeds up development. Much easier to learn after you understand vanilla CSS.'),
      h2('Common Mistakes That Slow You Down'),
      ul('Tutorial purgatory — Watching or reading tutorials without building anything yourself. Information without practice doesn\'t become skill.\nSkipping to frameworks — React is not beginner-friendly without fundamentals. Neither is Vue or Svelte. Do the boring work first.\nSwitching tools constantly — The best resource is the one you finish. Pick one and use it.\nComparing your progress to others — Some people learn in 6 months. Some take 2 years. The path is the same regardless of pace.\nGiving up when things break — Things will break. This is not failure — it\'s the most effective form of learning available.'),
      h2('Summary: The Ordered Path'),
      tb('Phase|What|Timeline\n1|HTML|1–2 weeks\n2|CSS|3–5 weeks\n3|JavaScript Fundamentals|4–6 weeks\n4|DOM Manipulation|2–3 weeks\n5|Capstone Project|2–4 weeks\n→|React / Backend / TypeScript|Ongoing'),
      p('Roughly 3–5 months of consistent daily practice to be genuinely capable of building real things. That\'s not fast. It\'s also not slow. It\'s the actual timeline.'),
      p('Devstiny teaches this exact path — HTML, CSS, JavaScript, and DOM — through an RPG-style narrative set in The Broken Realm. Each chapter is a realm with a story, companions, boss battles, and real code. Start your journey at devstiny.com.'),
    ],
  },

  // ─── 2: What Is HTML ───────────────────────────────────────────────────────
  {
    slug:        'what-is-html',
    title:       'What Is HTML? The Foundation of Every Website (Explained Simply)',
    excerpt:     'Learn what HTML is, how it works, and why every website on the internet starts with it. A beginner-friendly guide to HTML structure, tags, and semantic elements.',
    author:      'Elvar',
    tag:         'HTML',
    gem:         '/gem/gem-4.png',
    readTime:    8,
    isPublished: true,
    order:       2,
    body: [
      p('If you\'ve ever opened a website, you\'ve already used HTML — you just didn\'t know it.'),
      p('HTML (HyperText Markup Language) is the skeleton of every page on the internet. Before CSS adds color, before JavaScript adds interactivity, there is HTML: plain, structural, and essential.'),
      p('This guide covers everything you need to understand HTML from the ground up.'),
      h2('What Does HTML Actually Do?'),
      p('HTML doesn\'t make things look good. It doesn\'t add animations. It doesn\'t process data.'),
      p('What it does is describe structure and meaning. HTML tells the browser: "this is a heading," "this is a paragraph," "this is a navigation menu," "this is a button." The browser then knows how to handle each piece.'),
      p('Think of HTML as a blueprint for a building. The blueprint doesn\'t dictate the paint color or the furniture — it defines what rooms exist, where the doors are, and how everything connects.'),
      h2('The Anatomy of an HTML Document'),
      p('Every HTML page follows the same basic structure:'),
      c('<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <title>My First Page</title>\n  </head>\n  <body>\n    <h1>Hello, World</h1>\n    <p>This is a paragraph.</p>\n  </body>\n</html>'),
      p('Let\'s break that down:'),
      ul('<!DOCTYPE html> — Tells the browser this is an HTML5 document\n<html> — The root element that wraps everything\n<head> — Metadata the user doesn\'t see (title, charset, links to CSS)\n<body> — Everything the user does see'),
      p('One rule to remember: every tag that opens must close. <p> opens a paragraph. </p> closes it. A tag left open will bleed into surrounding elements — like a mold without a base.'),
      h2('Tags and Attributes'),
      p('HTML is built from tags — keywords wrapped in angle brackets. Most tags come in pairs: an opening tag and a closing tag.'),
      c('<h1>This is a heading</h1>\n<p>This is a paragraph</p>\n<a href="https://devstiny.com">This is a link</a>\n<img src="/image.png" alt="A description of the image">'),
      p('Attributes give extra information to a tag. In <a href="...">, the href attribute tells the browser where the link goes. In <img alt="...">, the alt attribute describes the image for screen readers and search engines.'),
      h2('Semantic HTML: Writing Code That Means Something'),
      p('Here\'s where most beginners take a shortcut they later regret.'),
      p('It\'s technically possible to build an entire website using only <div> tags. Visually, it might look fine. But to a search engine, a screen reader, or another developer reading your code — it\'s meaningless noise.'),
      p('Semantic HTML uses tags that describe what an element is, not just where it sits on screen:'),
      tb('Non-Semantic|Semantic\n<div class="header">|<header>\n<div class="nav">|<nav>\n<div class="main-content">|<main>\n<div class="footer">|<footer>\n<b>Important</b>|<strong>Important</strong>'),
      p('Why does this matter?'),
      ul('Accessibility — Screen readers use semantic tags to navigate pages for people who can\'t see them\nSEO — Search engines use heading hierarchy (<h1> through <h6>) to understand page structure\nReadability — Other developers (and future you) can understand the code at a glance'),
      h2('Common HTML Elements You\'ll Use Every Day'),
      tb('Element|Purpose\n<h1>–<h6>|Headings, largest to smallest\n<p>|Paragraph\n<a href="">|Link\n<img src="" alt="">|Image\n<ul> / <ol> / <li>|Unordered/ordered list and list items\n<div>|Generic container (use sparingly)\n<span>|Inline container for styling small pieces\n<button>|Clickable button\n<input>|Form input field\n<form>|Groups form elements'),
      h2('HTML and the Three Layers of the Web'),
      p('HTML doesn\'t work alone. Every website is built on three layers that work together:'),
      tb('Layer|Language|Role\nStructure|HTML|What exists and what it means\nPresentation|CSS|How it looks\nBehavior|JavaScript|What it does'),
      p('The order matters. You can\'t style something that doesn\'t exist. You can\'t add behavior to an element that isn\'t in the page. HTML always comes first.'),
      h2('How Browsers Read HTML'),
      p('When you type a URL and press Enter, here\'s what happens:'),
      ul('Your browser sends an HTTP request to a server\nThe server responds with an HTML file\nThe browser reads the HTML top to bottom and builds the DOM — a tree structure representing every element on the page\nCSS and JavaScript are then loaded and applied on top of that structure'),
      p('This is why HTML is called the foundation. Everything else is built on it.'),
      h2('What Comes Next'),
      p('HTML is the first language every web developer learns — and for good reason. It\'s straightforward, immediately visual, and the gateway to everything else on the web.'),
      p('Once you understand HTML, you\'re ready to learn CSS (how to make your pages look the way you want) and JavaScript (how to make them respond to user actions).'),
      p('The web is built from three languages. HTML is where you start.'),
      p('Ready to learn HTML through an actual story? In Devstiny, you learn HTML inside The Broken Realm — a world built from code that\'s slowly falling apart. Start your first chapter at devstiny.com.'),
    ],
  },

  // ─── 3: Semantic HTML ─────────────────────────────────────────────────────
  {
    slug:        'semantic-html',
    title:       'Semantic HTML: Why Using the Right Tags Actually Matters',
    excerpt:     'Most beginners write HTML with divs for everything. Here\'s why semantic HTML tags like header, nav, main, and section make your code better for SEO, accessibility, and maintainability.',
    author:      'Elvar',
    tag:         'HTML',
    gem:         '/gem/gem-9.png',
    readTime:    9,
    isPublished: true,
    order:       3,
    body: [
      p('Here\'s a line of code most beginners write without thinking:'),
      c('<div class="header">\n  <div class="nav">\n    <div class="nav-item">Home</div>\n  </div>\n</div>'),
      p('It works. The page renders. No errors. But to a search engine, a screen reader, or a developer reading your code three months from now — it says almost nothing useful.'),
      p('This is the difference between HTML that\'s technically correct and HTML that\'s semantically meaningful.'),
      h2('What Is Semantic HTML?'),
      p('Semantic HTML means using elements that describe the purpose and meaning of your content — not just how it looks. The word "semantic" comes from semantics: the study of meaning. A semantic element is one whose tag name tells you what the content is, not just how to render it.'),
      p('Compare these two navigation menus:'),
      c('<!-- Non-semantic -->\n<div class="navigation">\n  <div class="nav-link">Home</div>\n  <div class="nav-link">About</div>\n</div>\n\n<!-- Semantic -->\n<nav>\n  <a href="/">Home</a>\n  <a href="/about">About</a>\n</nav>'),
      p('Both might look identical in a browser. But the second one communicates its purpose clearly — to the browser, to search engines, to assistive technologies, and to other developers.'),
      h2('The Core Semantic Layout Elements'),
      p('HTML5 introduced a set of structural elements specifically designed to give meaning to page layout:'),
      h3('<header>'),
      p('The introductory content of a page or section. Typically contains the site logo, navigation, and page title.'),
      c('<header>\n  <img src="/logo.png" alt="Devstiny">\n  <nav>...</nav>\n</header>'),
      h3('<nav>'),
      p('A section containing navigation links — either the main site navigation or a set of links within a page.'),
      h3('<main>'),
      p('The primary content of the page. There should only be one <main> per page. This is the content unique to that specific page — not the header, footer, or sidebar.'),
      h3('<article>'),
      p('Self-contained content that could be removed from the page and still make sense on its own: a blog post, a news story, a forum post.'),
      h3('<section>'),
      p('A thematic grouping of content that belongs together. Unlike <article>, it\'s not self-contained — it\'s a chunk of a larger whole.'),
      h3('<aside>'),
      p('Content that\'s related to but separate from the main content: a sidebar, a related links panel, a callout box.'),
      h3('<footer>'),
      p('The closing content of a page or section: copyright, links, contact information.'),
      h2('Semantic Text Elements'),
      p('Beyond layout, HTML has semantic elements for inline text:'),
      tb('Element|Meaning|Don\'t Confuse With\n<strong>|Important, serious content|<b> (just bold, no meaning)\n<em>|Emphasized content, stress|<i> (just italic, no meaning)\n<h1>–<h6>|Hierarchical headings|Not for styling — for structure\n<time>|A date or time|<span> (generic, no meaning)\n<code>|Inline code snippet|<span class="code">\n<blockquote>|A quoted passage|<div class="quote">'),
      p('The visual output of <strong> and <b> might look the same in a browser. But <strong> tells a screen reader "this is important" — the reader may emphasize it in audio output. <b> just makes text bold with no semantic weight.'),
      h2('Why Semantic HTML Matters for SEO'),
      p('Search engines don\'t see your page the way humans do. They read the HTML structure and make decisions about what your page is about and how to rank it.'),
      p('A well-structured semantic page helps search engines:'),
      ul('Understand content hierarchy — <h1> is the main topic, <h2> is a subtopic. Google uses this hierarchy to understand your content\nFind the primary content — <main> signals where the real content is, vs. navigation or footers\nIndex articles and sections — <article> suggests self-contained content worth indexing independently\nRead dates and metadata — <time datetime="2025-01-15"> gives structured date information'),
      p('Every <div> you use instead of a semantic element is information you\'re not giving to search engines.'),
      h2('Why Semantic HTML Matters for Accessibility'),
      p('Over a billion people worldwide use assistive technologies like screen readers. Screen readers work by announcing HTML elements to users who can\'t see the screen.'),
      p('A screen reader on a <div class="nav"> reads: "div." Not helpful. A screen reader on <nav> reads: "navigation." The user knows exactly what this region is and can navigate directly to it using keyboard shortcuts.'),
      p('Most screen readers also provide a "landmarks" list — a quick-navigation menu of all the major page regions. Those landmarks are built entirely from semantic elements: header, nav, main, aside, footer. Write non-semantic HTML and your page becomes nearly unusable for people relying on screen readers.'),
      h2('Common Mistakes to Avoid'),
      ul('Using <div> for everything — Reach for a semantic element first. Only use <div> when no semantic element fits — as a pure styling container.\nUsing headings for size, not hierarchy — Don\'t use <h3> because you want smaller text. Use it because this content is a third-level topic under your <h2>. Use CSS for sizing.\nSkipping heading levels — Jump from <h1> to <h4> and screen readers lose the structure. Heading levels should flow in order: 1 → 2 → 3.\nNesting incorrectly — <p> elements cannot contain block-level elements. Structure matters.'),
      h2('A Complete Semantic Page Template'),
      c('<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>Article Title | Site Name</title>\n</head>\n<body>\n\n  <header>\n    <a href="/">Site Logo</a>\n    <nav>\n      <a href="/">Home</a>\n      <a href="/blog">Blog</a>\n    </nav>\n  </header>\n\n  <main>\n    <article>\n      <header>\n        <h1>Article Title</h1>\n        <p>Published <time datetime="2025-06-01">June 1, 2025</time></p>\n      </header>\n      <section>\n        <h2>First Major Topic</h2>\n        <p>Content goes here.</p>\n      </section>\n    </article>\n    <aside>\n      <h2>Related Articles</h2>\n    </aside>\n  </main>\n\n  <footer>\n    <p>© 2025 Your Site.</p>\n  </footer>\n\n</body>\n</html>'),
      h2('The Core Principle'),
      p('Semantic HTML is a habit, not a technique. Every time you write an element, ask: "Is there a tag that describes what this content is?" If the answer is yes — use it. If no tag fits, then and only then use a <div>.'),
      p('Your pages will rank better, work for more people, and be easier to maintain. Three benefits from the same decision.'),
      p('Devstiny teaches HTML through story-driven chapters in The Broken Realm. In Chapter 2, you rewrite the corrupted HTML structure of an entire realm — one semantic element at a time. Start learning at devstiny.com.'),
    ],
  },

  // ─── 4: CSS Box Model ─────────────────────────────────────────────────────
  {
    slug:        'css-box-model',
    title:       'The CSS Box Model Explained: Why Everything in CSS Is a Box',
    excerpt:     'The CSS box model is the single most important concept for understanding layout. Learn what content, padding, border, and margin do — and why box-sizing matters.',
    author:      'Elvar',
    tag:         'CSS',
    gem:         '/gem/gem-16.png',
    readTime:    8,
    isPublished: true,
    order:       4,
    body: [
      p('If there\'s one thing that explains why CSS layout feels confusing at first, it\'s this: every element on a page is a box. Not visually — you don\'t see the boxes. But structurally, every <div>, every <p>, every <h1>, every <img> occupies a rectangular space on the page, and the CSS Box Model defines exactly how that space is calculated.'),
      p('Once this clicks, a lot of CSS makes sense.'),
      h2('The Four Layers of the Box Model'),
      p('Every HTML element\'s box is made up of four concentric layers, from the inside out:'),
      ul('Content — The actual text, image, or child elements. The width and height properties control this layer.\nPadding — The space inside the border, between the content and the edge of the element. Padding is transparent — it takes on the background color of the element.\nBorder — The line drawn around the padding. You can control its width, style, and color.\nMargin — The space outside the border — the gap between this element and neighboring elements. Unlike padding, margin is always transparent.'),
      h3('Content'),
      p('The actual content of the element — the text, the image, the child elements. The width and height properties control this layer.'),
      h3('Padding'),
      p('The space inside the border, between the content and the edge. Padding is transparent — it takes on the background color of the element.'),
      c('.card {\n  padding: 24px;               /* all four sides */\n  padding: 16px 24px;          /* top/bottom | left/right */\n  padding: 8px 16px 24px 32px; /* top | right | bottom | left */\n}'),
      h3('Border'),
      p('The line drawn around the padding. You can control its width, style, and color.'),
      c('.card {\n  border: 2px solid #4ECDC4;\n  border-radius: 8px; /* rounded corners */\n}'),
      h3('Margin'),
      p('The space outside the border — the gap between this element and neighboring elements. Unlike padding, margin is always transparent.'),
      c('.card {\n  margin: 0 auto;       /* center horizontally */\n  margin-bottom: 24px;\n}'),
      h2('The Critical Problem: How Width Is Calculated'),
      p('Here\'s where most beginners get burned. By default, CSS calculates width as the width of the content area only. Padding and border are added on top of that.'),
      c('.box {\n  width: 200px;\n  padding: 20px;\n  border: 2px solid black;\n}'),
      p('The box you see on screen is actually 244px wide: 200px content + 20px left padding + 20px right padding + 2px left border + 2px right border. Set two of these to width: 50% and they won\'t fit side by side. This surprises almost every beginner.'),
      h2('The Fix: box-sizing: border-box'),
      p('The solution is one line of CSS, almost universally applied at the top of every stylesheet:'),
      c('*, *::before, *::after {\n  box-sizing: border-box;\n}'),
      p('With box-sizing: border-box, the width property now refers to the total visible width of the element — border and padding included. The content area shrinks to accommodate.'),
      c('.box {\n  width: 200px;\n  padding: 20px;\n  border: 2px solid black;\n  box-sizing: border-box;\n  /* Box on screen is exactly 200px */\n}'),
      p('Always use box-sizing: border-box. The default behavior (content-box) exists for historical reasons and causes more confusion than it\'s worth.'),
      h2('Padding vs. Margin: When to Use Which'),
      p('This trips up beginners constantly. Here\'s the practical rule: use padding when you want space inside an element — between its content and its edge. Use margin when you want space between elements — gaps in the layout between one box and the next.'),
      c('/* Padding: breathing room inside the button */\n.button {\n  padding: 12px 24px;\n  background-color: #FF6B6B;\n}\n\n/* Margin: gap between this button and the next element */\n.button {\n  margin-bottom: 16px;\n}'),
      p('If you\'re adding a background color or border and you want the space inside to match, use padding. If you\'re creating gaps between components in a layout, use margin.'),
      h2('Margin Collapse: The Behavior That Confuses Everyone'),
      p('Vertical margins between block elements have a quirk: they collapse. If one element has margin-bottom: 24px and the next has margin-top: 16px, you might expect 40px of space between them. Instead, you get 24px — the larger of the two values.'),
      c('.paragraph-one { margin-bottom: 24px; }\n.paragraph-two  { margin-top: 16px;    }\n/* Actual gap between them: 24px, not 40px */'),
      p('Margin collapse only happens with vertical margins between block elements. Horizontal margins don\'t collapse. Flexbox and Grid containers prevent margin collapse entirely.'),
      h2('Seeing the Box Model in Practice'),
      p('Every browser\'s DevTools has a box model visualizer. Open DevTools (F12), click on any element, and look at the "Computed" tab. You\'ll see a diagram showing the exact content, padding, border, and margin values for that element. This is one of the most useful tools for debugging layout issues.'),
      h2('Quick Reference'),
      tb('Property|What It Does\nwidth / height|Sets content size (or total size with border-box)\npadding|Space inside the element, between content and border\nborder|The line around the padding\nmargin|Space outside the element, between it and neighbors\nbox-sizing: border-box|Makes width/height include padding and border'),
      h2('The Takeaway'),
      p('The box model isn\'t a quirk of CSS — it\'s the foundation of everything. Every layout decision you make, every spacing problem you debug, traces back to these four layers.'),
      p('Learn the box model once, properly, and layout stops being mysterious.'),
      p('In Devstiny, CSS is taught through Chapter 3: The CSS Kingdom — where the entire realm has been locked by a corrupted custom property. Lyra, the realm\'s alchemist, becomes your guide through selectors, the box model, Flexbox, and Grid. Learn CSS through story at devstiny.com.'),
    ],
  },

  // ─── 5: JavaScript DOM Manipulation ───────────────────────────────────────
  {
    slug:        'javascript-dom-manipulation',
    title:       'JavaScript DOM Manipulation: How to Make Web Pages Actually Do Things',
    excerpt:     'Learn how JavaScript interacts with the DOM to select elements, change content, modify styles, and respond to user events. A practical beginner\'s guide to DOM manipulation.',
    author:      'Elvar',
    tag:         'JAVASCRIPT',
    gem:         '/gem/gem-21.png',
    readTime:    10,
    isPublished: true,
    order:       5,
    body: [
      p('HTML builds the structure. CSS makes it look right. But neither of them responds when a user clicks a button, fills out a form, or types into a search box.'),
      p('That\'s JavaScript\'s job — specifically, JavaScript\'s ability to read and rewrite the DOM. Understanding DOM manipulation is the moment web development stops being static and starts feeling alive.'),
      h2('What Is the DOM?'),
      p('When a browser loads an HTML page, it doesn\'t just display it — it builds a representation of the entire page in memory. This representation is called the Document Object Model, or DOM.'),
      p('The DOM is a tree. At the top is document — the entire page. Below that, every HTML element becomes a node: the <body> contains a <main>, which contains an <article>, which contains an <h1>, and so on, all the way down to the individual text inside each element.'),
      p('JavaScript can access this tree, walk through it, read it, and modify it. When JavaScript changes a node, the browser immediately updates what\'s visible on screen — no page reload required.'),
      h2('Step 1: Selecting Elements'),
      p('Before you can change anything, you need to find it. JavaScript gives you several ways to select elements from the DOM.'),
      h3('querySelector — Your Primary Tool'),
      c('// Select by CSS selector — returns the first match, or null\nconst heading = document.querySelector(\'h1\');\nconst button  = document.querySelector(\'.submit-btn\');\nconst panel   = document.querySelector(\'#user-panel\');'),
      p('querySelector accepts any valid CSS selector — tag names, classes, IDs, attribute selectors, combinators. It returns the first element that matches, or null if nothing matches.'),
      h3('querySelectorAll — When You Need Multiple Elements'),
      c('// Returns a NodeList of all matching elements\nconst allCards = document.querySelectorAll(\'.card\');\n\nallCards.forEach(card => {\n  console.log(card.textContent);\n});'),
      h3('Always Check for null'),
      c('const panel = document.querySelector(\'#user-panel\');\n\n// Without this check, your code crashes if the element doesn\'t exist\nif (panel) {\n  panel.style.display = \'block\';\n}'),
      p('If you call a method on null, you get a TypeError that crashes your script. Check first.'),
      h2('Step 2: Reading and Writing Content'),
      p('Once you have an element, you can read what\'s inside it and write new content.'),
      h3('textContent — Safe for Plain Text'),
      c('const title = document.querySelector(\'h1\');\n\n// Read\nconsole.log(title.textContent); // "Welcome to Devstiny"\n\n// Write\ntitle.textContent = \'Quest Complete\';'),
      p('textContent gets or sets the plain text of an element and all its descendants. It\'s safe because it doesn\'t parse HTML — if you write <strong> into textContent, it shows up as literal characters, not bold text.'),
      h3('innerHTML — For When You Need HTML'),
      c('const card = document.querySelector(\'.card\');\ncard.innerHTML = \'<h2>New Title</h2><p>New description.</p>\';'),
      p('innerHTML parses and renders HTML, so you can insert tags. But there\'s a critical warning: never set innerHTML from user input. If a user types <script>alert("hacked")</script> and you put that directly into innerHTML, it executes. This is called an XSS vulnerability. Use textContent for user-generated content, always.'),
      h2('Step 3: Changing Classes and Styles'),
      p('The cleanest way to change how an element looks is to add or remove CSS classes. Define the visual state in your CSS file, then toggle it with JavaScript.'),
      c('// In your CSS\n.hidden      { display: none; }\n.card--active { border-color: #4ECDC4; }\n\n// In your JavaScript\nconst card  = document.querySelector(\'.card\');\nconst modal = document.querySelector(\'.modal\');\n\ncard.classList.toggle(\'card--active\');  // Toggle on/off\nmodal.classList.add(\'hidden\');          // Add a class\nmodal.classList.remove(\'hidden\');       // Remove a class\n\nif (card.classList.contains(\'card--active\')) {\n  console.log(\'Card is active\');\n}'),
      p('Prefer classList — it keeps your CSS in your CSS file. You can also set inline styles directly, but this is generally less clean and should be avoided for anything defined in a stylesheet.'),
      h2('Step 4: Creating and Removing Elements'),
      p('JavaScript can build entirely new elements and add them to the page, or remove existing ones.'),
      c('// Create a new element\nconst newCard = document.createElement(\'div\');\nnewCard.className = \'card\';\nnewCard.textContent = \'New item\';\n\n// Add it to the page\nconst container = document.querySelector(\'.container\');\ncontainer.appendChild(newCard); // Adds at the end\ncontainer.prepend(newCard);     // Adds at the beginning\n\n// Remove an element\nconst oldItem = document.querySelector(\'.outdated-item\');\noldItem.remove();'),
      p('This is the foundation of dynamic web apps — when you load more results without refreshing the page, when you add items to a cart, when a notification appears in the corner — this is what\'s happening.'),
      h2('Step 5: Responding to Events'),
      p('The most important part of DOM manipulation is making things happen in response to what users do.'),
      h3('addEventListener'),
      c('const button = document.querySelector(\'#submit-btn\');\n\nbutton.addEventListener(\'click\', function(event) {\n  console.log(\'Button clicked\');\n  event.preventDefault(); // Prevent default form submission\n});'),
      p('The first argument is the event name. The second is a callback function that runs when the event fires.'),
      p('Common events:'),
      tb('Event|Triggers When\nclick|User clicks an element\nsubmit|A form is submitted\ninput|User types in an input field\nchange|A select/checkbox/radio changes\nkeydown|A key is pressed\nmouseenter / mouseleave|Mouse enters or leaves an element'),
      h3('Event Delegation: One Listener for Many Elements'),
      p('Adding individual listeners to 100 list items is inefficient. Event delegation attaches a single listener to a parent element and uses event.target to handle clicks on its children.'),
      c('const list = document.querySelector(\'.items-list\');\n\nlist.addEventListener(\'click\', function(event) {\n  // Check if a list item was clicked\n  if (event.target.matches(\'.item\')) {\n    event.target.classList.toggle(\'item--selected\');\n  }\n});\n\n// Works even for elements added to the list AFTER the listener was attached'),
      h2('Putting It Together: A Complete Example'),
      c('const input    = document.querySelector(\'#task-input\');\nconst addButton = document.querySelector(\'#add-btn\');\nconst taskList  = document.querySelector(\'#task-list\');\n\n// Add a task\naddButton.addEventListener(\'click\', function() {\n  const text = input.value.trim();\n  if (!text) return;\n\n  const li = document.createElement(\'li\');\n  li.className = \'task-item\';\n  li.textContent = text;\n\n  const removeBtn = document.createElement(\'button\');\n  removeBtn.textContent = \'×\';\n  removeBtn.className = \'remove-btn\';\n  li.appendChild(removeBtn);\n\n  taskList.appendChild(li);\n  input.value = \'\';\n});\n\n// Remove a task (event delegation)\ntaskList.addEventListener(\'click\', function(event) {\n  if (event.target.matches(\'.remove-btn\')) {\n    event.target.parentElement.remove();\n  }\n});'),
      h2('The Key Principles to Remember'),
      ul('Select before you modify — Always get a reference to the element first\nCheck for null — querySelector returns null if nothing matches; handle it\nUse classList over inline styles — Keep visual logic in CSS\nPrefer textContent for user content — innerHTML is powerful and dangerous\nEvent delegation scales better — One parent listener beats many child listeners'),
      h2('What Comes After DOM Manipulation'),
      p('Once you\'re comfortable with the DOM, the next territory is making network requests — fetching data from APIs without reloading the page (the Fetch API and async/await). After that, you\'ll find that frameworks like React are largely abstractions over the same ideas: selecting elements, managing state, and responding to events.'),
      p('The DOM is where JavaScript starts to feel like real power.'),
      p('In Devstiny\'s Chapter 4, the DOM is taught through The Wired District — a city where every element exists but nothing renders. Somers, the realm\'s jester-logician, guides you through selection, manipulation, and events to restore the district node by node. Start learning at devstiny.com.'),
    ],
  },
];

async function main() {
  console.log('Seeding blog posts...');
  for (const post of posts) {
    await prisma.blogPost.upsert({
      where:  { slug: post.slug },
      create: post as never,
      update: post as never,
    });
    console.log(`  ✓ ${post.slug}`);
  }
  console.log(`Done — ${posts.length} posts seeded.`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
